<?php // this is an autogenerated file - do not edit (created Tue, 09 Aug 2011 00:39:47 +0200)
spl_autoload_register(
   function($class) {
      static $classes = null;
      if ($classes === null) {
         $classes = array(
            'foodalizr\\controller\\mealcontroller' => '/controller/MealController.php',
            'foodalizr\\controller\\personcontroller' => '/controller/PersonControler.php',
            'foodalizr\\model\\contribution' => '/model/Contribution.php',
            'foodalizr\\model\\mapperabstract' => '/persistence/MapperAbstract.php',
            'foodalizr\\model\\mapperfactory' => '/persistence/MapperFactory.php',
            'foodalizr\\model\\meal' => '/model/Meal.php',
            'foodalizr\\model\\participation' => '/model/Participation.php',
            'foodalizr\\model\\person' => '/model/Person.php',
            'foodalizr\\model\\personmapper' => '/persistence/PersonMapper.php',
            'foodalizr\\model\\spending' => '/model/Spending.php',
            'knid\\math\\decimal' => '/Decimal.php'
          );
      }
      $cn = strtolower($class);
      if (isset($classes[$cn])) {
         require __DIR__ . $classes[$cn];
      }
   }
);
