<?php // this is an autogenerated file - do not edit (created Sun, 07 Aug 2011 12:20:56 +0200)
spl_autoload_register(
   function($class) {
      static $classes = null;
      if ($classes === null) {
         $classes = array(
            'foodalizr\\model\\person' => '/Person.php'
          );
      }
      $cn = strtolower($class);
      if (isset($classes[$cn])) {
         require __DIR__ . $classes[$cn];
      }
   }
);
