<?php // this is an autogenerated file - do not edit (created Wed, 10 Aug 2011 20:51:40 +0200)
spl_autoload_register(
   function($class) {
      static $classes = null;
      if ($classes === null) {
         $classes = array(
            'acme\\demobundle\\acmedemobundle' => '/Acme/DemoBundle/AcmeDemoBundle.php',
            'acme\\demobundle\\controller\\democontroller' => '/Acme/DemoBundle/Controller/DemoController.php',
            'acme\\demobundle\\controller\\securedcontroller' => '/Acme/DemoBundle/Controller/SecuredController.php',
            'acme\\demobundle\\controller\\welcomecontroller' => '/Acme/DemoBundle/Controller/WelcomeController.php',
            'acme\\demobundle\\controllerlistener' => '/Acme/DemoBundle/ControllerListener.php',
            'acme\\demobundle\\dependencyinjection\\acmedemoextension' => '/Acme/DemoBundle/DependencyInjection/AcmeDemoExtension.php',
            'acme\\demobundle\\form\\contacttype' => '/Acme/DemoBundle/Form/ContactType.php',
            'acme\\demobundle\\tests\\controller\\democontrollertest' => '/Acme/DemoBundle/Tests/Controller/DemoControllerTest.php',
            'acme\\demobundle\\twig\\extension\\demoextension' => '/Acme/DemoBundle/Twig/Extension/DemoExtension.php',
            'foodalizr\\controller\\mealcontroller' => '/controller/MealController.php',
            'foodalizr\\controller\\personcontroller' => '/controller/PersonControler.php',
            'foodalizr\\model\\contribution' => '/model/Contribution.php',
            'foodalizr\\model\\mapperabstract' => '/persistence/MapperAbstract.php',
            'foodalizr\\model\\mapperfactory' => '/persistence/MapperFactory.php',
            'foodalizr\\model\\meal' => '/model/Meal.php',
            'foodalizr\\model\\participation' => '/model/Participation.php',
            'foodalizr\\model\\person' => '/model/Person.php',
            'foodalizr\\model\\spending' => '/model/Spending.php',
            'knid\\io\\exception' => '/framework/Knid/Io/Exception.php',
            'knid\\io\\file' => '/framework/Knid/Io/File.php',
            'knid\\math\\decimal' => '/framework/Knid/Math/Decimal.php',
            'knid\\view' => '/framework/Knid/View.php',
            'knid\\view\\template' => '/framework/Knid/View/Template.php'
          );
      }
      $cn = strtolower($class);
      if (isset($classes[$cn])) {
         require __DIR__ . $classes[$cn];
      }
   }
);
